# -*- coding: utf-8 -*-
"""Stochastic models_alaka

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TH7e0frqFQ2pJHcZ7zOiqa-zOla-yE7u

Model 1
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files
import io

uploaded = files.upload()
print("Uploaded files:", list(uploaded.keys()))

filename = list(uploaded.keys())[0]

df = pd.read_csv(io.BytesIO(uploaded[filename]))

print("Data preview:")
print(df.head())

df['Date'] = pd.to_datetime(df['Date'].str.replace(' IST', ''), format='%Y-%m-%d %H:%M:%S %z')
df.sort_values('Date', inplace=True)
df.reset_index(drop=True, inplace=True)

df['Return'] = np.log(df['Close'] / df['Close'].shift(1))
df = df.dropna().reset_index(drop=True)

def compute_I(row):
    if row['High'] != row['Low']:
        return (row['Close'] - row['Open']) / (row['High'] - row['Low'])
    else:
        return 0

df['I'] = df.apply(compute_I, axis=1)

span = 20
df['P_eq'] = df['Close'].ewm(span=span, adjust=False).mean()

k = 0.01
lambda_mr = 0.05
dt = 1
rolling_window = span

predicted_prices = []
prediction_dates = []
actual_prices = []

for i in range(rolling_window, len(df)):
    window = df.iloc[i - rolling_window : i]

    mu_window = window['Return'].ewm(span=rolling_window, adjust=False).mean().iloc[-1]
    sigma_window = window['Return'].ewm(span=rolling_window, adjust=False).std().iloc[-1]

    I_last = window['I'].iloc[-1]

    P_last = window['Close'].iloc[-1]

    P_eq = df['P_eq'].iloc[i - 1]

    mr_term = -lambda_mr * (np.log(P_last) - np.log(P_eq))

    exponent = (mu_window + k * I_last + mr_term - 0.5 * sigma_window**2) * dt
    P_pred = P_last * np.exp(exponent)

    predicted_prices.append(P_pred)
    prediction_dates.append(df['Date'].iloc[i])
    actual_prices.append(df['Close'].iloc[i])

pred_df = pd.DataFrame({
    'Date': prediction_dates,
    'Predicted': predicted_prices,
    'Actual': actual_prices
})

plt.figure(figsize=(12, 6))
plt.plot(pred_df['Date'], pred_df['Actual'], label='Actual Close Price', marker='o')
plt.plot(pred_df['Date'], pred_df['Predicted'], label='Predicted Price', linestyle='--', marker='x')
plt.xlabel('Date')
plt.ylabel('Price')
plt.title('Refined Rolling Forecast: Predicted vs. Actual Prices')
plt.legend()
plt.grid(True)
plt.show()

#CSV saving

output_filename = 'refined_predictions.csv'
pred_df.to_csv(output_filename, index=False)
print("Predictions saved to '{}'.".format(output_filename))


files.download(output_filename)

"""Model 2"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files
import io
import plotly.graph_objects as go
from scipy.stats import linregress

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from xgboost import XGBRegressor
from sklearn.metrics import mean_absolute_error

#Importing CSV

uploaded = files.upload()
print("Uploaded files:", list(uploaded.keys()))
filename = list(uploaded.keys())[0]

df = pd.read_csv(io.BytesIO(uploaded[filename]))
print("Data preview:")
print(df.head())

df['Date'] = pd.to_datetime(df['Date'].str.replace(' IST', ''), format='%Y-%m-%d %H:%M:%S %z')
df.sort_values('Date', inplace=True)
df.reset_index(drop=True, inplace=True)

# Log returns

df['logP'] = np.log(df['Close'])

df['Return'] = df['logP'].diff()
df = df.dropna().reset_index(drop=True)

#Imbalance

def compute_I(row):
    if row['High'] != row['Low']:
        return (row['Close'] - row['Open']) / (row['High'] - row['Low'])
    else:
        return 0
df['I'] = df.apply(compute_I, axis=1)

#Others Terms

df['rolling_mean'] = df['Close'].rolling(window=10, min_periods=10).mean()
df['rolling_std'] = df['Return'].rolling(window=10, min_periods=10).std()
def compute_RSI(series, window=14):
    delta = series.diff()
    gain = delta.clip(lower=0)
    loss = -delta.clip(upper=0)
    avg_gain = gain.rolling(window=window, min_periods=window).mean()
    avg_loss = loss.rolling(window=window, min_periods=window).mean()
    rs = avg_gain / (avg_loss + 1e-8)
    return 100 - (100 / (1 + rs))
df['RSI'] = compute_RSI(df['Close'], window=14)

df = df.dropna().reset_index(drop=True)

features_list = []
target_list = []
dates_list = []

for t in range(10, len(df)-1):
    P_t = df['Close'].iloc[t]
    logP_t = df['logP'].iloc[t]
    roll_mean = df['rolling_mean'].iloc[t]
    roll_std = df['rolling_std'].iloc[t]

    window_prices = df['Close'].iloc[t-5:t].values
    times = np.arange(5)
    slope, _, _, _, _ = linregress(times, window_prices)

    I_t = df['I'].iloc[t]
    RSI_t = df['RSI'].iloc[t]
    momentum = logP_t - df['logP'].iloc[t-1]

    feature_vector = [P_t, roll_mean, roll_std, slope, I_t, RSI_t, momentum]
    features_list.append(feature_vector)

    r_target = df['logP'].iloc[t+1] - logP_t
    target_list.append(r_target)

    dates_list.append(df['Date'].iloc[t])

features = np.array(features_list)
targets = np.array(target_list)
dates = np.array(dates_list)

print("Feature matrix shape:", features.shape)
print("Target vector shape:", targets.shape)

#XGBoost regression

X_train, X_test, y_train, y_test, dates_train, dates_test = train_test_split(features, targets, dates, test_size=0.3, random_state=42)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

model = XGBRegressor(n_estimators=200, learning_rate=0.05, random_state=42)
model.fit(X_train_scaled, y_train)
y_pred_train = model.predict(X_train_scaled)
y_pred_test = model.predict(X_test_scaled)

mae_train = np.mean(np.abs(y_pred_train - y_train))
mae_test = np.mean(np.abs(y_pred_test - y_test))
print("Train MAE:", mae_train)
print("Test MAE:", mae_test)

#Predictiions

X_all_scaled = scaler.transform(features)
predicted_log_returns = model.predict(X_all_scaled)
predicted_prices = []
for i in range(len(predicted_log_returns)):
    P_t = features[i][0]
    P_pred = P_t * np.exp(predicted_log_returns[i])
    predicted_prices.append(P_pred)

actual_prices = []
for i in range(10, len(df)-1):
    actual_prices.append(df['Close'].iloc[i+1])
actual_prices = np.array(actual_prices)
pred_dates = dates

result_df = pd.DataFrame({
    'Date': pred_dates,
    'Actual': actual_prices,
    'Predicted': predicted_prices
})
result_df['Absolute_Error'] = np.abs(result_df['Predicted'] - result_df['Actual'])
result_df['Percentage_Error'] = 100 * result_df['Absolute_Error'] / result_df['Actual']

print("Prediction Results (first 10 rows):")
print(result_df.head(10))
print("Mean Percentage Error: {:.2f}%".format(result_df['Percentage_Error'].mean()))

#Plotting

import plotly.express as px
import plotly.graph_objects as go

fig = go.Figure()
fig.add_trace(go.Scatter(x=df['Date'], y=df['Close'],
                         mode='lines', name='Actual Price'))
fig.add_trace(go.Scatter(x=result_df['Date'], y=result_df['Predicted'],
                         mode='lines+markers', name='Predicted Price', line=dict(dash='dash')))
fig.update_layout(title='1-Minute Interval Stock Price Prediction',
                  xaxis_title='Time',
                  yaxis_title='Price',
                  hovermode='x unified')
fig.show()

#CSV file

output_filename = 'advanced_minute_prediction_results.csv'
result_df.to_csv(output_filename, index=False)
print("Prediction results saved to '{}'.".format(output_filename))
files.download(output_filename)

